jomminii/brandi-admin-clone-v2

- frontend/src/component/common/Input.js
- frontend/src/pages/Login.js
- input component 생성
- login page에 적용 후 레이아웃 1차 수정
> [Add Input Compnent]

- .gitignore
- backend/app.py
- backend/brandi.sql
- backend/manage.py
- backend/seller/model/model.py
- backend/seller/service/service.py
- backend/seller/view/view.py
- seller/model에 Error catch 부분 추가
> [Flask API 구조 설계]

- backend/app.py
- backend/seller/model/model.py
- backend/seller/service/service.py
- backend/seller/view/view.py
[Initial Tutorial]
- 테스트용 API(GET, POST)
> [Flask test API 추가]

- .gitignore
- backend/app.py
- backend/brandi.sql
- backend/seller/model/model.py
- backend/seller/view/view.py
- seller_info 테이블과 manager_info 테이블 동시 추가 트랜젝션 추가
- rollback 추가
> [초기 파일 transaction 추가]

- backend/app.py
- backend/seller/model/model.py
- backend/seller/service/service.py
- backend/seller/view/view.py
- 설명 주석용 docstring format을 reStructuredText에서 Google로 변경
> [API 주석 포맷 변경]

- backend/seller/model/model.py
- backend/seller/service/service.py
- backend/seller/view/view.py
- seller sevice에서 inser_new_seller함수가  new seller data를 인자로 바로 받는 것에서 request인자를 받도록 수정
- 받은 request에서 body를 json으로 변환하여 model로직으로 전달함.
- minor : model 로직에서 INSERT문 가독성을 위해 행 분리
> [seller service 로직 request인자 추가]

- .gitignore
- 셀러 어드민 전체 스키마와 샘플 데이터를 sql script로 작성
- mysql에서 source로 부르면 기존 DB(brandi)가 삭제되고, 새로운 
DB(brandi)를 만들어 스크립트를 실행하도록 설정
> [SQL script(schema) v1.0 업로드]

- .gitignore
- backend/schema/brandi_schema_v1.0.sql
[gitignore에서 *.sql 제거 및 schema 재업로드]
> [gitignore에서 *.sql 제거 및 schema 재업로드]

- backend/app.py
- backend/manage.py
- backend/schema/brandi_schema_v1.0.sql
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- seller 고객 센터 운영시간 자료형 timedelta를 json으로 다루기 위해 app.CustomEncoder 수정
- DB collation 호환 문제로 utf8mb_0900_ai_ci -> utf8mb_general_ci 로 변경
> [seller 운영시간 자료형 문제 해결 및 DB collation 변경]

- backend/app.py
- backend/connection.py
- backend/manage.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- Database 연결 관련 에러 캐치 처리
- 포맷 안맞는 함수 주석 설명 수정
> [db connection 관련 error 캐치]

- backend/connection.py
- backend/image/view/image_view.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- backend/utils.py
- 로그인 데코레이터 등록
- db connection error catch 추가
> [Login decorator 등록]

- backend/image/service/image_service.py
- backend/image/view/image_view.py
- backend/schema/brandi_schema_v1.4.sql
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- requirements.txt
- 데코레이터에서 넘어온 유저정보를 확인하여 마스터 권한이면 셀러 리스트를 표출
- sql 파일 수정
> [셀러 리스트 표출 API]

- backend/app.py
- backend/manage.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/seller/service/seller_service.py
- backend/utils.py
- 상품 수정하기 전 기존에 있던 상품 상세 정보 표출
> [상품 수정 > 상품 기존 정보 표출]

- backend/image/service/image_service.py
- backend/schema/brandi_schema_v1.4.sql
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- 쿼리파라미터로 키워드를 받아서 검색
- request 파라미터 유효성검사
- 셀러 리스트 pagitation 추가
> [마스터 권한 셀러 리스트 검색기능 추가]

- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- DB_CURSOR_ERROR / NO_DATABASE_CONNECTION 에러의 상태코드를 400에서
500으로 변경
- change_password / get_seller_info 기능에서 INVALID_KEY 에러 제거.
파라미터 유효성검사에서 체크됨
> [DB 관련 에러메시지 상태코드 변경 및 INVALID KEY ERROR 제거]

- backend/manage.py
- backend/product/model/product_dao.py
- backend/product/view/product_view.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- 마스터 권한으로 상품 등록시 셀러 한글 이름으로 검색
> [상품 등록 > 셀러 검색]

- backend/image/service/image_service.py
- backend/image/view/image_view.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- 셀러 리스트 표출로 셀러별 상태 변경 명령어 확인
- 마스터 권한을 가진 유저의 셀러 상태 변경
- 변경하고자 하는 셀러 아이디와 셀러 상태 아이디를 받아서 변경
> [PUT 마스터 권한 셀러 상태 변경]

- backend/connection.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/seller/model/seller_dao.py
- backend/seller/view/seller_view.py
1. Database connector 모듈 변경
mysql.connector 에서 pymysql.connector로 변경하였음
> [Database 커넥터 변경 mysql.connector -> pymysql.connector]

- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
[로그인 API 구현]
- 로그인 처리 후 유효기간 담긴 토큰 발행
[DB connection 변수 변경]
- view.py에서 db_connection = DatabaseConnection() 를 -> db_connection = get_db_connection() 으로 변경
- dao.py에서 with db_connection as db_cursor 를 -> with db_connection.cursor() as db_cursor
> [로그인 > 로그인 API 구현 및 DB connection 변수 일부 변경]

- frontend/src/component/common/CustomButton.js
- frontend/src/component/common/ImageUploader.js
- frontend/src/component/common/Input.js
- frontend/src/component/common/InputContainer.js
- frontend/src/component/common/SmallButton.js
- frontend/src/component/common/Validation.js
- frontend/src/component/sellerInfoEdit/Main.js
- frontend/src/component/sellerInfoEdit/SellerProperty.js
- frontend/src/utils/regexp.js
- SignUp 페이지
- SignUp 페이지 정규식 Validation 판별 기능 추가
- Input 컴포넌트 Validation 관련 기능 추가
- Validation 컴포넌트 Validation 관련 기능 추가
- Input과 Validation을 담은 Container Component 추가
> [SignUp Page | Add Components, Validation]

- frontend/src/component/common/Input.js
- frontend/src/component/common/InputContainer.js
- frontend/src/component/common/Validation.js
- frontend/src/component/sellerInfoEdit/Main.js
- Input 컴포넌트 필수입력 아닐 경우 아무값도 없을 떄 Validation 띄우지 않도록 수정
> [Input Component 수정]

- frontend/src/Routes.js
- frontend/src/component/common/Input.js
- frontend/src/component/common/Validation.js
- frontend/src/pages/Login.js
- frontend/src/pages/LoginOk.js
- frontend/src/pages/SignUp.js
- frontend/src/utils/config.js
- frontend/src/utils/regexp.js
[pages > signup page]
- login page API 연동을 위한 fetch 함수 구현
- login page HTML, CSS 완료
- signup page API 연동을 위한 fetch 함수 구현
- signup page validation 함수 추가
- signup page HTML, CSS 완료
- login 완료시 확인가능한 임시loginOk page 추가
- 각 page에 Route 추가
> [pages > login page]

- frontend/package-lock.json
- frontend/package.json
- frontend/src/component/common/ImageUploader.js
- frontend/src/component/common/InfoText.js
- frontend/src/component/common/Input.js
- frontend/src/component/common/InputContainer.js
- frontend/src/component/common/Layout.js
- frontend/src/component/common/Validation.js
- frontend/src/component/sellerInfoEdit/BusinessHour.js
- frontend/src/component/sellerInfoEdit/Main.js
- frontend/src/component/sellerInfoEdit/ManagerInfoItem.js
- frontend/src/component/sellerInfoEdit/ManagerRemoveButton.js
- frontend/src/component/sellerInfoEdit/PasswordModal.js
- frontend/src/component/sellerInfoEdit/SellerProperty.js
- frontend/src/component/sideBar/SideBar.js
- frontend/src/index.html
- frontend/src/index.js
- frontend/src/utils/config.js
- frontend/src/utils/regexp.js
- 담당자 추가 삭제 구현
- 비밀번호 변경 Modal 구현
> [셀러정보 수정 페이지 컴포넌트 추가, UI 추가]

- backend/app.py
- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/schema/brandi_schema_v1.6.sql
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- requirements.txt
유효성검사 수정]
[기획전(이벤트, 쿠폰) 등록 API 작성]
- 기획전 등록 관련 전체 필드에 대한 유효성 검사 실시
- 각 기획전 타입에 따른 필수값 통과여부 검사
- 기획전 기간 유효성 확인(현재보다 전인지, 시작시간이 종료시간보다
늦은지)
- 기획전 등록에 따른 events / event_infos / event_detail_infos 테이블 행 생성 완료
[회원가입 center_number 유효성검사 수정]
- 기존 가운데 부분의 허용 숫자를 4개로 고정한것을 3~4개로 변경
> [기획전(이벤트) 등록(POST) API 작성 및 회원가입 center_number

- backend/seller/model/seller_dao.py
- backend/seller/view/seller_view.py
추가확인]
- 선분이력 관리를 위한 시작일시 / 종료일시 기준 변경
-> 기존 : 새로 만든 셀러정보이력의 등록된 시간을 가져다가 이전
셀러정보의 시간 변경
-> 변경 : 최 상단에서 select now() 를 사용하여 특정 시간을 선언하고, 이
시간 기준으로 시작일시 / 종료일시 적용
- 이전 셀러정보의 (셀러상태, 종료일시) 변경 및 확인을 위해 사용하는 이전
셀러정보의 아이디 값 가져오는 방식 변경
-> 기존 : UI에서 request.body에 이전 셀러정보 아이디를 보내도록 요청
-> 변경 : 해당 셀러의 가장 최근 이력 정보를 조회해 이전 셀러정보
아이디를 최 상단에서 선언해놓고 가져다 씀
> [셀러정보 수정PUT - 선분이력 관리방식 및 이전셀러정보 관련 유효성

- backend/seller/model/seller_dao.py
- backend/seller/view/seller_view.py
- 셀러와 마스터의 권한에 따라 보여지는 페이지를 다르게 하기위해 UI에
권한정보 추가 제공
> [셀러 정보 표출 시 권한정보 추가 제공]

- backend/app.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/schema/brandi_schema_v1.7.sql
- backend/schema/brandi_schema_v1.8.sql
- backend/seller/model/seller_dao.py
- backend/seller/view/seller_view.py
- 마스터/셀러가 상품을 등록함
- 셀러가 올린 이미지는 S3를 거쳐 url을 받아 저장함.
- 현재 이미지 url은 mock data
- 시간 표출 형식 변경
> [setting 변경 및 상품 등록 > S3 거친 이미지 등록 추가]

- backend/app.py
- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/seller/model/seller_dao.py
- 기획전 타입이 쿠폰인 기획전을 등록하는 API
- 쿠폰 기획전의 필수값을 확인하고, 기획전 기간 등의 유효성을 확인한 후 기획전 등록 진행
> [쿠폰 기획전 등록]

- backend/app.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/schema/brandi_schema_v1.8.sql
- backend/utils.py
- requirements.txt
- 셀러 혹은 마스터 권한으로 상품의 상세 정보 수정 가능
- 상품 이미지 등록/수정 처리 완료
> [상품 관리 > 상품 수정]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/image/service/image_service.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- backend/utils.py
- 기획전 상품 이미지, 상품 텍스트, 유튜브 등록 api 작성
- 상품 정보가 들어오면 기획전용 상품 테이블에 저장.
- 기획전 타입 별로 들어와야하는 필수 값 validation
> [POST 기획전 등록]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/schema/brandi_schema_v2.0.sql
- backend/utils.py
- 이벤트 기획전 수정 api 작성
- 직전 기획전 정보와 비교하여 이벤트 타입 / 속성을 변경시키려하면 불가하다고 리턴
- 이미지 업로더가 완전히 만들어지지 않아 일단 상품 이미지 업로더 사용하여, 업로드 된 url 을 받아 저장하도록 처리
- 새로 파일이 업로드 되지 않을 경우, UI 에서 전달받은 url로 수정하도록 처리
- > 선분이력 적용 예정
> [PUT - 이벤트 기획전 수정]

- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
[제한 조건 추가]
- 변경할 비밀번호 길이가 4글자 미만이면 에러 반환 (‘TOO_SHORT_PASSWORD’)
- 존재하지 않는 계정의 비밀번호 변경을 요청하면 에러 반환. row count = 0 특성 이용.(‘INVALID_PARAMETER_ACCOUNT_NO’)
[인자명 수정]
- 전달 인자 명칭을 명확히 하기 위해 변경(account_info -> change_info)
[sql 바인딩 데이터 변경]
- get_account_password 와 change_password dao 에서 sql 바인딩을 위해 사용한 데이터 변경
- (기존) 바인딩을 위해 새로운 dict 를 정의해서 사용
- (변경) 인자로 받아온 change_info 에 담긴 데이터를 그대로 사용
> [제한 조건 추가 / sql 바인딩 데이터 변경 / 인자명 수정]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/schema/brandi_schema_v2.2.sql
- backend/seller/view/seller_view.py
- backend/utils.py
[PUT - 셀러 수정]
- 공통 이미지 업로더 적용
-> 기존 : 셀러 전용 이미지 업로더 사용
-> 변경 : 공통 이미지 업로더 사용
[POST/PUT - 기획전 등록/수정]
(공통)
- 공통 이미지 업로더 적용
-> 기존 : 기획전 전용 이미지 업로더 사용
-> 변경 : 공통 이미지 업로더 사용
- 에러 메시지 통일
-> 기존 : NO와 MISSING 혼용
-> 변경 : NO로 통일. ex) NO_DETAIL_IMAGE
- 기획전 타입이 상품, 유튜브 일 경우 기획전 종류 유효성 확인 추가
-> 선택된 기획전 타입에 해당되는 기획전 종류가 아니면 에러 반환
- 기획전 상품 정보를 json loads로 파싱하는 과정을 try/except 방식에서 if 문 방식으로 변경
(기획전 등록)
- event_type_id 를 str 로 받아오던 것에서 int 로 받아오도록 변경
> [공통 이미지 업로더 적용(셀러 수정, 기획전 등록/수정) 외 일부 내용 수정]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/seller/view/seller_view.py
- backend/utils.py
-등록된 기획전을 시작 날짜, 끝나는 날짜, 기획전 이름, 기획전 종류로 검색할 수 있음
> [기획전 관리 > 필터링 리스트 표출]

- backend/connection.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- action추가하는 부분에서 리스트로 뿌려줬었는데 딕셔너리로 리턴.
- 키 : action종류,  value: 액션을 누르면 실재로 바꿔야할 상태 아이디
[마스터 권한 셀러 상태 변경 PUT]
- 이전의 셀러 상태와 같은 값이 들어오면 애러 리턴
> [셀러 리스트 GET]

- backend/event/model/event_dao.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
> [이벤트 상품 GET]

- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
[VIEW]
- 주석 내용 보완
- 쿼리파라미터 유효성 검사 추가
- 마스터 권한이 아니면 접근 불가 처리(NO_AUTHORIZATION)
- db connection try/except 추가
- 셀러속성 쿼리 값을 리스트 형태로 받도록 변경
[SERVICE]
- 마스터 권한 확인을 view 에서 하도록 변경(db connection 열리기 전에)
- 사용되지 않는 user 인자 제거
- try / except 추가
[DAO]
- offset / limit 유효성 view 에서 확인하도록 이동
- 조회기간 필터 추가
- 필터링 부분 일부 리팩토링
> [GET - 상품 리스트 수정]

- backend/event/model/event_dao.py
- backend/product/view/product_view.py
- backend/seller/view/seller_view.py
- 사용하지 않게 된 account_no를 사용하지 않도록 변경
> [PUT - 셀러 정보 수정]

- frontend/package-lock.json
- npm start가 되지 않던 문제를 해결했습니다.
> [package-lock.json 문제 헤결]

- backend/seller/model/seller_dao.py
-셀러 상태 변경 시 셀러 상태 변경 이력테이블에 row 추가
> [셀러상태변경 put]

- backend/product/model/product_dao.py
- backend/product/view/product_view.py
- 첫번쨰 상품 대표이미지가 등록되지 않을 시 에러 반환
- 모든 상품 이미지가 1번부터 차례대로 들어오지 않으면 에러 반환
> [상품 등록 > 이미지 등록]

- backend/event/view/event_view.py
- backend/product/view/product_view.py
- backend/seller/model/seller_dao.py
- backend/seller/view/seller_view.py
- 셀러, 상품, 기획전 전부 적용
- connection을 열때 try를 시작하도록 변경
- connection이 있으면 파라미터를 서비스로 넘기고,  없으면 애러 리턴
- connection을 여는과정에서 애러가나면 exception으로 잡아줌.
- finally문으로 connection을 어떤 상황에도 닫아줌.
> [데이터베이스 커넥션 try-catch 수정]

- backend/product/model/product_dao.py
- 토큰 소지한 계정과 상품의 셀러가 다를 경우 에러 반환
> [상품 수정 권한 설정 변경]

- backend/event/model/event_dao.py
- WHERE AND NULL 사용 -> WHERE 1=1 사용
> [검색 필터링 스트링 바인딩 방법 변경]

- backend/event/view/event_view.py
- backend/image/service/image_service.py
- backend/product/view/product_view.py
- backend/seller/view/seller_view.py
- backend/utils.py
- 상품 이미지 업로더에 파일 확장자 체크해서 리사이즈하고, 업로드 하는 함수 scope동안 메모리상에 기존에 들어왔던 확장자로 저장되도록 만듦.
- 기획전 셀러 이미지등록에서 string에 업로드 되던거 파일객체가 업로드 되도록 바꿈.
> [이미지 업로더 수정]

- backend/product/model/product_dao.py
- backend/product/view/product_view.py
- 기존 : f-string 으로 sql 문에 직접적으로 파라미터를 넣는 방식
- 변경 : %(parameter)s 형식으로 DB 안에서 바인딩이 될 수 있도록 변경
+ SQL JOIN 문에서 약어 사용하도록 변경
+ 주석 추가
> [GET - 상품 리스트 _ 필터링 형식 파라미터 바인딩으로 변경 및 주석 추가]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- backend/utils.py
이벤트타입 3-5이면 기획전 상품이 안들어오면 에러 리턴
기획전 등록할 때 타입별 들어오지 말아야 할 키값이 들어오면 에러 리턴.
[주석 정리]
- 코드 설명 추가.
> [기획전 등록/수정]

- backend/app.py
- backend/connection.py
- backend/event/view/event_view.py
- backend/manage.py
- backend/product/model/product_dao.py
- backend/product/view/product_view.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- 셀러계정번호 존재 여부 확인
- 셀러명 중복체크 추가(이전 셀러정보와 비교해서, 기존 자신의 셀러명과 같으면 통과, 기존 자신의 셀러명과 다르면 중복체크 진행)
> [셀러 정보 수정 및 전체 VIEW 순서 배열 정리]

- backend/product/view/product_view.py
- json.lodas(args[17]) -> args[17]
- param(17, str) -> param(17, list)
변경
> [상품 등록 > list 자료형 변환]

- frontend/src/GlobalStyles.js
- frontend/src/component/productRegist/ColorFilter.js
- frontend/src/component/productRegist/SellerSelect.js
- frontend/src/component/productRegist/Wysiwyg.js
- frontend/src/pages/ProductRegist.js
- frontend/src/utils/config.js
- 셀러검색 API 받으면 리스트가 옆으로 나오는 부분 css 수정
- 셀러검색 API 받아서 들어오는 이미지 안들어오는 부분 해결
- postData에 초기값 설정 수정
- 1차 카테고리 선택시 2차 카테고리 받아오고 1차, 2차 setPostData시킴
- 상품정보고시 defaultValue 에러 해결
- 이미지등록시 postData에 이미지 파일 담기도록 수정
- 간편업로드 텍스트 postData에 setPostData 연결시킴
- 할인정보 기간설정부분 postData랑 연결시킴
- 태그 postData에 담기도록 수정
> [poroductRegist page]

- backend/event/model/event_dao.py
- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/product/view/product_view.py
- 필터링 된 모든 이벤트 수 표출
- 각 이벤트에 포함된 상품의 수 표출
- offset, limit 이용하여 페이지네이션 추가
> [이벤트 관리 > 목록 표출]

- backend/event/service/event_service.py
- backend/event/view/event_view.py
- backend/product/model/product_dao.py
- backend/product/service/product_service.py
- backend/product/view/product_view.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
[product_view]
- 주석 추가
- Exception error 코드 400 -> 500
[product_service]
- 주석 추가
- Exception error 코드 400 -> 500
[product_dao]
- SQL 문에 별칭 적용
- (insert_new_product) : 해당 셀러가 존재하지 않을 경우 에러 반환 추가
[그외]
- Exception error 코드 400 -> 500
> [상품 전체 정돈]

- frontend/src/Routes.js
- frontend/src/component/signup/PwdInput.js
- frontend/src/component/signup/PwdInputContainer.js
- frontend/src/component/signup/PwdValidation.js
- frontend/src/pages/Login.js
- frontend/src/pages/ProductModify.js
- frontend/src/pages/SignUp.js
- frontend/src/utils/config.js
- productModify page 추가
[login, signup page]
- password 암호화 부분 수정
> [productModify page]

- backend/seller/model/seller_dao.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/Routes.js
- frontend/src/component/common/ImageUploader.js
- frontend/src/component/productManagement/EnhancedTableHead.js
- frontend/src/component/productManagement/Main.js
- frontend/src/component/sellerAccountManagement/TestingTable.js
- frontend/src/component/sellerInfoEdit/Main.js
- frontend/src/component/sellerInfoEdit/PasswordModal.js
- frontend/src/index.js
- frontend/src/pages/Login.js
- frontend/src/pages/ProductManagement.js
- frontend/src/utils/config.js
- frontend/src/utils/regexp.js
- 이미지 업로드 구현 완료
- 담당자 정보 추가 삭제 에러 고침
- 기타 버그들 수정
[상품 리스트 구현]
- 상품 전체 목록 한번에 표시하도록 구현
> [셀러 수정 페이지 구현 완료]

- backend/product/model/product_dao.py
- backend/product/view/product_view.py
> [1차 카테고리 숫자 validation]

- frontend/src/Routes.js
- frontend/src/component/common/Header.js
- frontend/src/component/productManagement/Main.js
- frontend/src/component/sellerAccountManagement/TestingTable.js
- frontend/src/component/sellerInfoEdit/Main.js
- frontend/src/component/sellerInfoEdit/PasswordModal.js
- frontend/src/component/sideBar/SubMenuItem.js
- frontend/src/pages/Login.js
- frontend/src/pages/SignUp.js
- frontend/src/utils/config.js
- 네비게이션바 페이지 링크 구현
- 헤더 로그아웃 버튼 구현
> [네비게이션바, 헤더]

- backend/product/model/product_dao.py
- backend/seller/model/seller_dao.py
- backend/seller/service/seller_service.py
- backend/seller/view/seller_view.py
- SQL 문 별칭 적용
[SellerDao > get_seller_info]
- 입점대기 상태인 계정은 로그인 못하도록 제한 추가
[SellerDao > get_seller_info]
-  로그인 시 입점대기 여부를 확인하기 위해 상태 정보 셀렉트 추가
[ProductDao > get_product_list]
- 등록순 정렬 추가
> [Seller 전체 정리]

- frontend/src/Routes.js
- frontend/src/component/common/Input.js
- frontend/src/component/productManagement/Main.js
- frontend/src/component/sellerAccountManagement/TestingTable.js
- frontend/src/component/sellerInfoEdit/Main.js
- frontend/src/utils/config.js
- 셀러 마이 페이지 구현
- 기존의 셀러 수정페이지에서 셀러와 마스터의 권한에 따라 화면과 로직을 다르게 처리하도록 기능 추가
- 기본 route 경로 수정
> [셀러 마이 페이지]

- backend/product/model/product_dao.py
- backend/seller/model/seller_dao.py
- frontend/src/utils/config.js
- 등록순 정렬로 변경
[SellerDao > get_seller_info]
- 필요없는 삭제여부 조건 삭제
> [Product_dao > get_product_list]

- frontend/src/component/productManagement/Main.js
- frontend/src/component/productRegist/SellerSelect.js
- frontend/src/pages/ProductRegist.js
- frontend/src/utils/config.js
- 회원가입시 토큰발급이 필요하다고 뜨는 에러를 수정했습니다.
- 상품등록 fetch시 날짜가 제대로 입력되지 않던 부분을 수정했습니다.
- 상품등록 fetch시 seller account nunmer가 제대로 선택되지 않던 부분을 수정했습니다.
> [ signup, productRregist page 오류수정했습니다 ]
